# Generated by Django 5.1.1 on 2025-02-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diseinatzailea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('izena', models.CharField(max_length=75)),
                ('abizena', models.CharField(max_length=75)),
                ('helbidea', models.CharField(max_length=75)),
                ('emaila', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Jantzia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deskripzioa', models.CharField(max_length=75)),
                ('kolorea', models.CharField(max_length=75)),
                ('kopurua', models.IntegerField(max_length=10)),
            ],
        ),
    ]
