# Generated by Django 5.1.1 on 2025-02-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArropaAriketa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jantzia',
            name='kopurua',
            field=models.IntegerField(),
        ),
    ]
