# Generated by Django 5.1.1 on 2025-02-13 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArropaAriketa', '0002_alter_jantzia_kopurua'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bilduma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diseinatzailea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArropaAriketa.diseinatzailea')),
                ('jantzia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArropaAriketa.jantzia')),
            ],
        ),
    ]
